tests: fix panic for unpack test
Throws a panic like below when run TestUnpack test case:

```
converter_test.go:415:
Error Trace:	converter_test.go:415
Error:      	Not equal:
              expected: "sha256:b4679f7afa21a5513d84ba7d9a6faf2621f101421c830648512cd63475118fa1"
              actual  : "sha256:92ad2fb1075eabd299daa2dbb5e822031c198551fa9cebf29046ed79efa27ce3"

              Diff:
              --- Expected
              +++ Actual
              @@ -1,2 +1,2 @@
              -(digest.Digest) (len=71) "sha256:b4679f7afa21a5513d84ba7d9a6faf2621f101421c830648512cd63475118fa1"
              +(digest.Digest) (len=71) "sha256:92ad2fb1075eabd299daa2dbb5e822031c198551fa9cebf29046ed79efa27ce3"

Test:       	TestUnpack
```

Related: https://github.com/dragonflyoss/image-service/pull/630

To make the unpacked tar consistent with the OCI-formatted tar before the pack,
we need to backfill the username and groupname in the tar header, which may
break the repeatable build when unpacking in different hosts, but actually has
little effect.

Signed-off-by: Yan Song <imeoer@linux.alibaba.com>